# Generated by Django 3.0 on 2022-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.TextField(db_index=True, help_text='Короткая ссылка', verbose_name='Короткая ссылка')),
                ('original_link', models.TextField(help_text='Первоначальная ссылка', verbose_name='Первоначальная ссылка')),
                ('expires', models.DateTimeField(help_text='Дата прекращения действия', verbose_name='Дата прекращения действия')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-id'],
            },
        ),
    ]
